### ISSUE TITLE
[question] number of parameters 

### ISSUE THREAD

**Issue by xiuliren** [colehurwitz/IBL_foundation_model#30]
I am wondering how big this model is, but can not find the number of parameters in the paper.
could you help to answer this question?

**Comment by yzhang511** [comment]
Hello, the 34-session pre-trained NDT1 model has around 1 million parameters if we do not account for the session-specific stitchers (linear matrices). If we count the session stitchers, then it has 25.55 million parameters.

**Comment by xiuliren** [comment]
thank you for the response!



For the training data, only number of sessions is shared in the paper. could you also share some more statistics of the training data? For example, channel * hours of recording, neurons * hours of recording.

 

is the training data publicly available?

According to the shared data in the following link, it is not clear which data was used in the training.

https://www.internationalbrainlab.com/data

Best,

Jingpeng

**Comment by yzhang511** [comment]
Hi Jingpeng,

The training data is publicly available here: https://huggingface.co/ibl-foundation-model
If you click to join the organization, you can see the private datasets there which include all the sessions we used. 
We also documented which sessions are used for training and test purposes. 

While I don't have the exact numbers for the statistics of the training data, each session has 384 or 768 channels, and an average of 676 neurons per session. We have a total of 26,376 neurons for training and test. Although the whole recording is usually 1 hour, we only use the 2 second window around a "trial" within a recording, during which the stimulus is presented. Each session has 200 to 700 trials of 2 seconds long. Based on this, the estimated hours of recording is around 8 to 10 hours. 

Please let me know if you have further questions.

**Comment by xiuliren** [comment]
Hi Yizi,

thank you for the reply!

it seems that you only used a small part of the IBL dataset for this foundation model training, right ?
(26376/676)=39 sessions

according to the main IBL paper,  there are 354 sessions in total. 

If so, the total training data is only 10*768=7680 channel*h, right?

**Comment by yzhang511** [comment]
Yes, we only used a small part of the IBL reproducible ephys datasets (39/110 sessions).
I believe there are over 300 sessions in the full brain-wide-map datasets. 
Not all sessions have 768 channels. If there are 2 probes inserted in a session, then there are 2 x 384 channels. 

The total training data is 10*768=7680 channel*h.
Not sure what you mean by the "total coverage".

**Comment by xiuliren** [comment]
"total coverage" means the data before you extract the 2s stimulated time domain.

**Comment by xiuliren** [comment]
I have another question for the paper.
it claims multi-task capability, however, it seems not clear which downstream tasks are tested.

**Comment by yzhang511** [comment]
I see, then the total coverage is < 39 x 1 x 768 = 29,952 channel x h.
We tested 6 tasks, including 4 neural activity reconstruction tasks (leave-one-neuron-out co-smoothing, forward prediction, inter-region co-smoothing and intra-region co-smoothing) and 2 behavior decoding tasks (choice and WME).

**Comment by xiuliren** [comment]
I see. Thank you for the information!
